"""Property-based tests of the run loop, the memory-prompt helpers and seeding.

Oracle strategy
---------------
The run loop is checked against ``naive_run`` in ``tests/helpers.py``: three nested ``for``
loops that *render the prompts themselves* (string concatenation, no template engine, no shared
code) and ask a scripted model whose answer is a pure function of ``(model, seed, exact prompt)``.
Because the answer depends on the whole prompt, one comparison of the recorded answers against
the oracle proves at once that

* every (item, model, persona, seed) cell got the answer of *its* prompt - also when calls run
  concurrently and finish out of order (the model sleeps a prompt-dependent time),
* the prompts were rendered correctly, including the answers a persona remembers in cumulative
  mode and the escaping of braces, percent signs and newlines in those answers,
* callbacks, ``get_answers`` and ``get_answers_as_dataframe`` list the results in the documented
  order (callbacks: model, seed, item, persona; dataframe: item, model, persona, seed).

Grids (items 1-5, personas 1-4, seeds 1-3, models 1-2, ``max_concurrency`` 1-4) and failure
patterns (a model fails for a random subset of personas) are generated by Hypothesis.

``_escape`` and the memory-prompt builder are checked by formatting a prompt built from escaped
text back and comparing with the text. Seeding is checked on the offline tiny Hugging Face model:
equal seeds give equal samples, distinct seeds give varied ones, and the order in which seeds
are used does not matter.

Where the library violates an intended invariant, the property is written for the correct
behaviour and marked ``xfail(strict=True)`` with an ``@example`` that reproduces the bug.
"""

from __future__ import annotations

import logging
import threading
import time
import warnings
import zlib
from typing import Any

import pytest
from hypothesis import HealthCheck, example, given, settings
from hypothesis import strategies as st
from langchain_core.language_models.llms import LLM
from langchain_core.output_parsers import StrOutputParser
from langchain_core.prompts import ChatPromptTemplate, PromptTemplate
from pydantic import Field, PrivateAttr, ValidationError

import rupsycho as rup
from rupsycho.callbacks import Callback
from rupsycho.mixins import experiment_processing as processing
from rupsycho.models.parameters import ExperimentParameters
from rupsycho.seeding import seed_model

from .helpers import (
    PERSONA_RE,
    QUESTION_RE,
    SYSTEM_TEMPLATE,
    USER_TEMPLATE,
    Grid,
    build_config,
    chat_prompt_string,
    expected_answers,
    expected_rows,
    hash_answer,
    naive_run,
    plain,
    template_from_parts,
)

PROFILE = settings(
    max_examples=40,
    deadline=None,
    suppress_health_check=[HealthCheck.too_slow],
    print_blob=True,
)
LIGHT = settings(PROFILE, max_examples=25)


class ModelDown(RuntimeError):
    """The error the scripted model raises."""


class ScriptedLLM(LLM):
    """Deterministic fake model.

    Its answer is a pure function of ``(tag, seed, prompt)``, or - if ``script`` is given - the
    scripted text of the (persona, item) it recognises in the prompt. It records every prompt,
    can fail for chosen personas and can sleep a prompt-dependent time to scramble the order in
    which concurrent calls finish.
    """

    tag: str = "model"
    seed: int | None = None
    fail_personas: frozenset[int] = frozenset()
    script: dict[tuple[int, int], str] | None = None
    jitter: bool = False
    calls: list[Any] = Field(default_factory=list)
    _lock: Any = PrivateAttr(default_factory=threading.Lock)

    @property
    def _llm_type(self) -> str:
        return "scripted"

    def _call(self, prompt, stop=None, run_manager=None, **kwargs) -> str:
        persona = int(PERSONA_RE.search(prompt).group(1))  # the system message names it first
        item = int(QUESTION_RE.findall(prompt)[-1])  # the live question is the last one
        with self._lock:
            self.calls.append((self.seed, persona, item, prompt))
        if self.jitter:
            time.sleep(0.0004 * (zlib.crc32(prompt.encode()) % 4))
        if persona in self.fail_personas:
            raise ModelDown(f"{self.tag} cannot answer as persona {persona}")
        if self.script is not None:
            return self.script[(persona, item)]
        return hash_answer(self.tag, self.seed, prompt)


class Recorder(Callback):
    """Callback that remembers every answer in the order it is delivered."""

    def __init__(self) -> None:
        self.rows: list[tuple[Any, ...]] = []

    def save_answer(self, experiment, item_id, item, model_id, profile_id, seed, time, answer):
        self.rows.append((item_id, model_id, profile_id, seed, answer))


class LogCapture(logging.Handler):
    """Collects the records of the run loop's logger."""

    def __init__(self) -> None:
        super().__init__(level=logging.WARNING)
        self.records: list[logging.LogRecord] = []

    def emit(self, record: logging.LogRecord) -> None:
        self.records.append(record)


@pytest.fixture(scope="module", autouse=True)
def no_garbage_collection_between_models():
    """Skip the full ``gc.collect()`` the run loop performs after every model.

    With PyTorch loaded one collection takes about 100 ms - far more than the 20-120 scripted
    calls of an example - and releasing memory is not what these properties are about.
    """
    with pytest.MonkeyPatch.context() as patch:
        patch.setattr(
            processing.ExperimentProcessingMixin,
            "_cleanup_memory",
            lambda self: None,
            raising=False,
        )
        yield


# =============================================================================
# Strategies
# =============================================================================

MODEL_IDS = ("gpt-4o", "org/model:v1", "weird %s {id}", "m", "model 2", "\xe9t\xe9")

SPECIAL_FRAGMENTS = [
    "{",
    "}",
    "{{",
    "}}",
    "{}",
    "{0}",
    "{name}",
    "{question}",
    "{answer_options}",
    "{persona_description}",
    "%",
    "%s",
    "%(x)s",
    "100%",
    "\n",
    "\r\n",
    "\t",
    "\\",
    "$",
    "${x}",
    "{% if x %}",
    "{{ x }}",
    "\xe9",
    "\U00004e2d\U00006587",
    "\U0001f600",
    "\U00002028",
    " ",
    "",
]
RESERVED = "\U000027e6\U000027e7\xab\xbb"  # the markers and tags of the oracle
rich_text = st.one_of(
    st.text(
        alphabet=st.characters(exclude_categories=("Cs",), exclude_characters=RESERVED),
        max_size=20,
    ),
    st.lists(st.sampled_from(SPECIAL_FRAGMENTS), max_size=6).map("".join),
)


@st.composite
def grids(draw, *, failures: bool = True) -> Grid:
    """A random experiment shape: items, personas, seeds, models, option layouts, failures."""
    n_items = draw(st.integers(1, 5))
    n_personas = draw(st.integers(1, 4))
    seeds = draw(st.lists(st.integers(0, 10_000), min_size=1, max_size=3, unique=True))
    models = tuple(draw(st.lists(st.sampled_from(MODEL_IDS), min_size=1, max_size=2, unique=True)))
    item_options = tuple(
        draw(
            st.one_of(st.none(), st.tuples(st.sampled_from([", ", " | ", "\n", ""]), st.booleans()))
        )
        for _ in range(n_items)
    )
    personas = st.sets(st.integers(0, n_personas - 1), max_size=n_personas)
    failing = tuple(frozenset(draw(personas)) if failures else frozenset() for _ in models)
    return Grid(
        n_items=n_items,
        n_personas=n_personas,
        seeds=tuple(str(seed) for seed in seeds),
        models=models,
        item_options=item_options,
        failing=failing,
    )


concurrency = st.integers(1, 4)


# =============================================================================
# Helpers
# =============================================================================


def build_experiment(grid: Grid, *, script=None, jitter: bool = False, trailing=()):
    """The experiment of ``grid`` with one scripted model per model identifier.

    ``trailing`` lists further chat messages (``{"role": ..., "content": ...}``) appended to the
    two-message prompt template.
    """
    config = build_config(grid)
    config["prompt_template"]["messages"].extend(trailing)
    experiment = rup.experiment_from_dict(config)
    models = {}
    for index, model_id in enumerate(grid.models):
        model = ScriptedLLM(
            tag=model_id, fail_personas=grid.failing[index], script=script, jitter=jitter
        )
        experiment.add_model(model, identifier=model_id)
        models[model_id] = model
    return experiment, models


def answer_function(script):
    """``answer_of`` of the oracle for a model with (or without) a script."""
    if script is None:
        return lambda model, seed, persona, item, prompt: hash_answer(model, seed, prompt)
    return lambda model, seed, persona, item, prompt: script[(persona, item)]


def expected_error_messages(grid: Grid, calls) -> list[str]:
    """The distinct failure messages in call order, as ``RunSummary.errors`` lists them."""
    messages: list[str] = []
    for call in calls:
        if call.answer is None:
            message = f"ModelDown: {grid.models[call.model_index]} cannot answer as persona {call.persona}"
            if message not in messages:
                messages.append(message)
    return messages[:5]


def run_and_check(grid: Grid, *, cumulative: bool, max_concurrency: int, script=None, jitter=False):
    """Run ``grid`` and compare everything observable with the oracle's replay."""
    experiment, models = build_experiment(grid, script=script, jitter=jitter)
    recorder = Recorder()
    summary = experiment.run(
        callbacks=[recorder],
        cumulative=cumulative,
        max_concurrency=max_concurrency,
        on_error="ignore",
        show_progress=False,
    )
    calls = naive_run(grid, answer_function(script), cumulative=cumulative)

    # counters
    assert summary.n_calls == len(calls) == grid.n_calls
    assert summary.n_failed == grid.n_failing_calls == sum(c.answer is None for c in calls)
    assert summary.n_succeeded == summary.n_calls - summary.n_failed
    assert summary.errors == expected_error_messages(grid, calls)
    assert summary.elapsed >= 0

    # every callback, in the order the calls are made (identical for any max_concurrency)
    assert recorder.rows == [
        (
            c.item,
            grid.models[c.model_index],
            grid.persona_id(c.persona),
            grid.seeds[c.seed_index],
            c.answer,
        )
        for c in calls
    ]

    # the prompts each model received
    for index, model_id in enumerate(grid.models):
        expected = [
            (int(grid.seeds[c.seed_index]), c.persona, c.item, c.prompt)
            for c in calls
            if c.model_index == index
        ]
        seen = models[model_id].calls
        assert len(seen) == len(expected) == grid.n_items * grid.n_personas * len(grid.seeds)
        if max_concurrency == 1:
            assert seen == expected  # one at a time: even the order of the calls is fixed
        else:
            assert sorted(seen) == sorted(expected)

    # what is stored: one row per answered cell, in the documented order
    assert experiment.get_answers_as_dataframe().to_dict("records") == expected_rows(grid, calls)
    assert [plain(answers) for answers in experiment.get_answers()] == expected_answers(grid, calls)
    return experiment, summary, recorder, calls


# =============================================================================
# C. The run loop against the nested-loop oracle
# =============================================================================


class TestRunLoop:
    @PROFILE
    @given(grid=grids(failures=False), workers=concurrency)
    def test_a_run_makes_every_call_and_stores_every_answer(self, grid, workers):
        _, summary, _, _ = run_and_check(grid, cumulative=False, max_concurrency=workers)
        assert summary.n_failed == 0
        assert summary.n_calls == grid.n_items * grid.n_personas * len(grid.seeds) * len(
            grid.models
        )

    @PROFILE
    @given(grid=grids(), workers=concurrency)
    def test_failing_personas_are_counted_and_leave_no_rows(self, grid, workers):
        experiment, summary, _, calls = run_and_check(
            grid, cumulative=False, max_concurrency=workers
        )
        rows = experiment.get_answers_as_dataframe()
        failing_ids = {
            (grid.models[m], grid.persona_id(j))
            for m, personas in enumerate(grid.failing)
            for j in personas
        }
        assert not any(
            (r["Model ID"], r["Persona ID"]) in failing_ids for r in rows.to_dict("records")
        )
        assert len(rows) == summary.n_succeeded

    @LIGHT
    @given(grid=grids())
    def test_callbacks_and_results_do_not_depend_on_max_concurrency(self, grid):
        outcomes = []
        for workers in (1, 2, 3, 4):
            experiment, _, recorder, _ = run_and_check(
                grid, cumulative=False, max_concurrency=workers, jitter=True
            )
            outcomes.append(
                (recorder.rows, experiment.get_answers_as_dataframe().to_dict("records"))
            )
        assert all(outcome == outcomes[0] for outcome in outcomes)

    @LIGHT
    @given(grid=grids(), workers=concurrency)
    def test_cumulative_runs_follow_the_oracle_too(self, grid, workers):
        run_and_check(grid, cumulative=True, max_concurrency=workers, jitter=True)

    @LIGHT
    @given(grid=grids(), workers=concurrency, cumulative=st.booleans())
    def test_rerunning_an_experiment_gives_identical_results(self, grid, workers, cumulative):
        experiment, models = build_experiment(grid)

        def run_once():
            recorder = Recorder()
            summary = experiment.run(
                callbacks=[recorder],
                cumulative=cumulative,
                max_concurrency=workers,
                on_error="ignore",
                show_progress=False,
            )
            frame = experiment.get_answers_as_dataframe().to_dict("records")
            return recorder.rows, frame, (summary.n_calls, summary.n_failed, summary.errors)

        first, second = run_once(), run_once()
        assert first == second
        assert all(
            len(model.calls) == 2 * grid.n_items * grid.n_personas * len(grid.seeds)
            for model in models.values()
        )

        fresh, _ = build_experiment(grid)
        fresh.run(cumulative=cumulative, on_error="ignore", show_progress=False)
        assert fresh.get_answers_as_dataframe().to_dict("records") == first[1]

    @LIGHT
    @given(grid=grids(failures=False), workers=concurrency)
    def test_the_dataframe_has_one_row_per_cell_in_the_documented_order(self, grid, workers):
        experiment, _, _, _ = run_and_check(grid, cumulative=False, max_concurrency=workers)
        frame = experiment.get_answers_as_dataframe()
        cells = list(
            zip(frame["Instruction ID"], frame["Model ID"], frame["Persona ID"], frame["Run Seed"])
        )
        expected = [
            (i, model, grid.persona_id(j), seed)
            for i in range(grid.n_items)
            for model in grid.models
            for j in range(grid.n_personas)
            for seed in grid.seeds
        ]
        assert cells == expected
        assert len(set(cells)) == len(cells)


class TestCollection:
    @LIGHT
    @given(grids=st.lists(grids(), min_size=1, max_size=3), workers=concurrency)
    def test_run_all_runs_every_experiment_and_returns_one_summary_each(self, grids, workers):
        built = [build_experiment(grid) for grid in grids]
        collection = rup.ExperimentCollection([experiment for experiment, _ in built])
        summaries = collection.run_all(
            max_concurrency=workers, on_error="ignore", show_progress=False
        )
        assert len(summaries) == len(grids)
        for (experiment, _), grid, summary in zip(built, grids, summaries):
            calls = naive_run(grid, answer_function(None))
            assert (summary.n_calls, summary.n_failed) == (grid.n_calls, grid.n_failing_calls)
            assert experiment.get_answers_as_dataframe().to_dict("records") == expected_rows(
                grid, calls
            )


class TestErrorPolicy:
    @PROFILE
    @given(grid=grids())
    def test_warn_reports_failures_once_and_logs_each(self, grid):
        experiment, _ = build_experiment(grid)
        capture = LogCapture()
        logger = logging.getLogger("rupsycho.mixins.experiment_processing")
        logger.addHandler(capture)
        try:
            with warnings.catch_warnings(record=True) as caught:
                warnings.simplefilter("always")
                summary = experiment.run(show_progress=False)  # on_error="warn" is the default
        finally:
            logger.removeHandler(capture)
        runtime_warnings = [w for w in caught if issubclass(w.category, RuntimeWarning)]
        if grid.n_failing_calls:
            assert len(runtime_warnings) == 1
            assert f"{summary.n_failed} of {summary.n_calls} model calls failed" in str(
                runtime_warnings[0].message
            )
        else:
            assert runtime_warnings == []
        failures = [r for r in capture.records if "Model call failed" in r.getMessage()]
        assert len(failures) == grid.n_failing_calls

    @PROFILE
    @given(grid=grids())
    def test_ignore_is_silent(self, grid):
        experiment, _ = build_experiment(grid)
        capture = LogCapture()
        logger = logging.getLogger("rupsycho.mixins.experiment_processing")
        logger.addHandler(capture)
        try:
            with warnings.catch_warnings(record=True) as caught:
                warnings.simplefilter("always")
                summary = experiment.run(on_error="ignore", show_progress=False)
        finally:
            logger.removeHandler(capture)
        assert [w for w in caught if issubclass(w.category, RuntimeWarning)] == []
        assert capture.records == []
        assert summary.n_failed == grid.n_failing_calls

    @PROFILE
    @given(grid=grids(), workers=concurrency, cumulative=st.booleans())
    def test_raise_stops_at_the_first_failing_call(self, grid, workers, cumulative):
        experiment, models = build_experiment(grid)
        recorder = Recorder()
        calls = naive_run(grid, answer_function(None), cumulative=cumulative)
        failing = [position for position, c in enumerate(calls) if c.answer is None]

        def run():
            return experiment.run(
                callbacks=[recorder],
                cumulative=cumulative,
                max_concurrency=workers,
                on_error="raise",
                show_progress=False,
            )

        if not failing:
            run()
            assert len(recorder.rows) == len(calls)
            return
        with pytest.raises(ModelDown, match="cannot answer"):
            run()
        first = failing[0]
        # results are delivered in call order, so exactly the calls before the failure arrive
        assert len(recorder.rows) == first
        assert all(row[-1] is not None for row in recorder.rows)
        made = sum(len(model.calls) for model in models.values())
        assert made >= first + 1
        if workers == 1:
            assert made == first + 1  # nothing is asked after the failure

    @PROFILE
    @given(grid=grids(failures=False))
    def test_invalid_arguments_are_rejected_before_any_call(self, grid):
        experiment, models = build_experiment(grid)
        for kwargs in ({"on_error": "explode"}, {"max_concurrency": 0}, {"max_concurrency": -2}):
            with pytest.raises(ValueError):
                experiment.run(show_progress=False, **kwargs)
        assert all(model.calls == [] for model in models.values())


# =============================================================================
# C. Cumulative mode with arbitrary answer texts
# =============================================================================


@st.composite
def cumulative_scenarios(draw):
    """A failure-free grid and a scripted answer text for every (persona, item)."""
    grid = draw(grids(failures=False))
    script = {(j, i): draw(rich_text) for j in range(grid.n_personas) for i in range(grid.n_items)}
    return grid, script


class TestCumulativeMode:
    @PROFILE
    @given(scenario=cumulative_scenarios(), workers=concurrency)
    def test_any_answer_text_is_remembered_literally_and_never_breaks_a_run(
        self, scenario, workers
    ):
        grid, script = scenario
        _, summary, _, _ = run_and_check(
            grid, cumulative=True, max_concurrency=workers, script=script
        )
        assert summary.n_failed == 0

    @PROFILE
    @given(scenario=cumulative_scenarios(), workers=concurrency)
    def test_a_later_prompt_contains_the_earlier_answers_of_its_persona_only(
        self, scenario, workers
    ):
        grid, script = scenario
        # make every answer identifiable: tag it with the persona and item it belongs to
        tagged = {(j, i): f"\xab{j}.{i}\xbb{text}" for (j, i), text in script.items()}
        experiment, models = build_experiment(grid, script=tagged)
        experiment.run(
            cumulative=True, max_concurrency=workers, on_error="ignore", show_progress=False
        )
        for model in models.values():
            for _seed, persona, item, prompt in model.calls:
                for other_persona in range(grid.n_personas):
                    for earlier in range(grid.n_items):
                        answer = tagged[(other_persona, earlier)]
                        remembered = other_persona == persona and earlier < item
                        assert (answer in prompt) is remembered, (persona, item, answer)

    @PROFILE
    @given(grid=grids(failures=False))
    def test_the_first_question_of_a_persona_is_asked_like_in_a_plain_run(self, grid):
        plain_experiment, plain_models = build_experiment(grid)
        plain_experiment.run(show_progress=False)
        memory_experiment, memory_models = build_experiment(grid)
        memory_experiment.run(cumulative=True, show_progress=False)
        for model_id in grid.models:
            first_questions = {
                (seed, persona): prompt
                for seed, persona, item, prompt in plain_models[model_id].calls
                if item == 0
            }
            remembered = {
                (seed, persona): prompt
                for seed, persona, item, prompt in memory_models[model_id].calls
                if item == 0
            }
            assert remembered == first_questions

    @PROFILE
    @given(grid=grids(), workers=concurrency)
    def test_a_failed_answer_is_not_remembered(self, grid, workers):
        experiment, models = build_experiment(grid)
        experiment.run(
            cumulative=True, max_concurrency=workers, on_error="ignore", show_progress=False
        )
        for model in models.values():
            # a remembered failure would read "... ->" followed by "None" in a later prompt
            assert not any("-> None" in prompt for _, _, _, prompt in model.calls)


def test_further_messages_of_the_template_survive_in_cumulative_mode():
    grid = Grid(
        n_items=2,
        n_personas=1,
        seeds=("1",),
        models=("m",),
        item_options=(None, None),
        failing=(frozenset(),),
    )
    priming = [{"role": "ai", "content": "My answer is:"}]
    first_prompts = {}
    for cumulative in (False, True):
        experiment, models = build_experiment(grid, trailing=priming)
        try:
            experiment.run(cumulative=cumulative, show_progress=False)
        except ValueError:
            assert cumulative  # refusing a template that cumulative mode cannot honour is fine
            return
        first_prompts[cumulative] = models["m"].calls[0][3]
    assert first_prompts[True] == first_prompts[False]


# =============================================================================
# C. Empty answer options
# =============================================================================


def test_an_item_with_empty_options_uses_the_default_options_in_its_prompt():
    """Items 'without options of their own' fall back to the defaults (see PostprocessingPipeline)."""
    config = build_config(
        Grid(
            n_items=1,
            n_personas=1,
            seeds=("1",),
            models=("m",),
            item_options=(None,),
            failing=(frozenset(),),
        )
    )
    config["questionnaire"]["instruction_items"][0]["answer_options"] = {}
    experiment = rup.experiment_from_dict(config)
    model = ScriptedLLM(tag="m")
    experiment.add_model(model, identifier="m")
    experiment.run(show_progress=False)
    assert "Options: 1. never, 2. often |" in model.calls[0][3]


# =============================================================================
# D. Escaping text for prompt templates
# =============================================================================

any_text = st.one_of(rich_text, st.text(max_size=30))


class TestEscape:
    @PROFILE
    @given(text=any_text)
    def test_a_chat_prompt_built_from_escaped_text_formats_back_to_the_text(self, text):
        prompt = ChatPromptTemplate.from_messages(
            [("system", "s"), ("human", processing._escape(text))]
        )
        assert prompt.input_variables == []
        assert prompt.format_messages()[1].content == text

    @PROFILE
    @given(text=any_text)
    def test_a_plain_prompt_built_from_escaped_text_formats_back_to_the_text(self, text):
        prompt = PromptTemplate.from_template(processing._escape(text))
        assert prompt.input_variables == []
        assert prompt.format() == text

    @PROFILE
    @given(before=any_text, after=any_text, value=any_text)
    def test_escaped_text_does_not_disturb_the_placeholders_around_it(self, before, after, value):
        prompt = PromptTemplate.from_template(
            f"{processing._escape(before)}{{x}}{processing._escape(after)}"
        )
        assert prompt.input_variables == ["x"]
        assert prompt.format(x=value) == before + value + after

    @PROFILE
    @given(first=any_text, second=any_text)
    def test_escaping_is_compatible_with_concatenation(self, first, second):
        assert processing._escape(first + second) == processing._escape(first) + processing._escape(
            second
        )


class TestSafeFormat:
    @PROFILE
    @given(
        values=st.dictionaries(st.sampled_from(["question", "answer_options", "name"]), any_text),
        parts=st.lists(
            st.one_of(
                st.tuples(st.just("lit"), any_text),
                st.tuples(st.just("ph"), st.sampled_from(["question", "answer_options", "name"])),
                st.tuples(st.just("ph"), st.sampled_from(["unknown", "x1"])),
            ),
            max_size=8,
        ),
    )
    def test_known_placeholders_are_filled_and_unknown_ones_stay_as_they_are(self, values, parts):
        template = template_from_parts(parts)
        # unknown placeholders come back as "{name}"; known ones as their value
        expected = "".join(
            text if kind == "lit" else (str(values[text]) if text in values else "{" + text + "}")
            for kind, text in parts
        )
        assert template.format_map(processing._SafeFormat(values)) == expected


summaries = st.builds(
    rup.RunSummary,
    n_calls=st.integers(0, 50),
    n_failed=st.integers(0, 50),
    elapsed=st.floats(0, 100, allow_nan=False),
    errors=st.lists(st.sampled_from(["a", "b", "c", "d", "e", "f", "g"]), max_size=5, unique=True),
)


def first_five_distinct(messages):
    """The oracle of how summaries merge their error messages."""
    distinct: list[str] = []
    for message in messages:
        if message not in distinct:
            distinct.append(message)
    return distinct[:5]


class TestRunSummary:
    @PROFILE
    @given(first=summaries, second=summaries)
    def test_adding_summaries_adds_the_counters_and_merges_the_errors(self, first, second):
        total = first + second
        assert total.n_calls == first.n_calls + second.n_calls
        assert total.n_failed == first.n_failed + second.n_failed
        assert total.elapsed == first.elapsed + second.elapsed
        assert total.errors == first_five_distinct(first.errors + second.errors)

    @PROFILE
    @given(first=summaries, second=summaries, third=summaries)
    def test_addition_is_associative_and_has_a_neutral_element(self, first, second, third):
        left, right = (first + second) + third, first + (second + third)
        assert (left.n_calls, left.n_failed, left.errors) == (
            right.n_calls,
            right.n_failed,
            right.errors,
        )
        neutral = first + rup.RunSummary()
        assert (neutral.n_calls, neutral.n_failed, neutral.errors) == (
            first.n_calls,
            first.n_failed,
            first.errors,
        )

    @PROFILE
    @given(summary=summaries)
    def test_derived_values_follow_the_counters(self, summary):
        assert summary.n_succeeded == summary.n_calls - summary.n_failed
        expected = f"{summary.n_calls} model calls in {summary.elapsed:.1f}s"
        if summary.n_failed:
            expected += f", {summary.n_failed} failed"
        assert str(summary) == expected


@st.composite
def memory_scenarios(draw):
    """A conversation history and the live inputs of the next question."""
    history = draw(st.lists(st.tuples(any_text, any_text), max_size=5))
    inputs = {
        "persona_description": draw(any_text),
        "general_instruction": draw(any_text),
        "question": draw(any_text),
        "answer_options": draw(any_text),
    }
    return history, inputs


class TestMemoryPrompt:
    @PROFILE
    @given(scenario=memory_scenarios())
    def test_the_history_is_inserted_literally_before_the_live_question(self, scenario):
        history, inputs = scenario
        chat = ChatPromptTemplate.from_messages(
            [("system", SYSTEM_TEMPLATE), ("user", USER_TEMPLATE)]
        )
        prompt = processing.ExperimentProcessingMixin()._memory_prompt(history, *chat.messages)

        system, human = prompt.format_messages(**inputs)
        live = (
            f"Q: {inputs['question']} | Options: {inputs['answer_options']} "
            '| A: {"answer": "<x>"} ->'
        )
        assert system.content == (
            f"You are {inputs['persona_description']}. {inputs['general_instruction']}"
        )
        assert human.content == "".join(f"{q} {a}\n" for q, a in history) + live
        assert sorted(prompt.input_variables) == sorted(inputs)

    @PROFILE
    @given(scenario=memory_scenarios())
    def test_the_string_a_plain_model_receives_is_the_two_messages(self, scenario):
        history, inputs = scenario
        chat = ChatPromptTemplate.from_messages(
            [("system", SYSTEM_TEMPLATE), ("user", USER_TEMPLATE)]
        )
        prompt = processing.ExperimentProcessingMixin()._memory_prompt(history, *chat.messages)
        system, human = prompt.format_messages(**inputs)
        assert prompt.invoke(inputs).to_string() == chat_prompt_string(
            system.content, human.content
        )


# =============================================================================
# E. Seeding on the offline tiny Hugging Face model
# =============================================================================

SEED_PROMPT = ChatPromptTemplate.from_messages([("user", "{x}")])
valid_seeds = st.integers(0, 2**32 - 1)
SEEDING = settings(PROFILE, max_examples=8)


@pytest.fixture(scope="module")
def tiny_model(tiny_hf_dir):
    """The tiny local model, loaded once for all examples of this module."""
    from rupsycho.models.model import LocalHuggingFaceModelConfig

    from .tiny_hf import TINY_PARAMETERS

    config = LocalHuggingFaceModelConfig(
        name_or_path=str(tiny_hf_dir),
        device_map="cpu",
        task="text-generation",
        parameters=dict(TINY_PARAMETERS),
    )
    return config.load_model()


def sample(model, seed, text="hello"):
    chain = SEED_PROMPT | seed_model(model, seed) | StrOutputParser()
    return chain.invoke({"x": text})


class TestSeeding:
    @SEEDING
    @given(seed=valid_seeds, text=st.text(alphabet="abc xyz", min_size=1, max_size=6))
    def test_the_same_seed_gives_the_same_sample(self, tiny_model, seed, text):
        assert sample(tiny_model, seed, text) == sample(tiny_model, seed, text)
        assert sample(tiny_model, str(seed), text) == sample(tiny_model, seed, text)  # "7" is 7

    @SEEDING
    @given(seeds=st.lists(valid_seeds, min_size=3, max_size=5, unique=True))
    def test_distinct_seeds_give_varied_samples(self, tiny_model, seeds):
        assert len({sample(tiny_model, seed) for seed in seeds}) >= 2

    @SEEDING
    @given(seeds=st.lists(valid_seeds, min_size=2, max_size=4, unique=True), data=st.data())
    def test_a_sample_does_not_depend_on_the_order_the_seeds_are_used_in(
        self, tiny_model, seeds, data
    ):
        shuffled = data.draw(st.permutations(seeds))
        forwards = {seed: sample(tiny_model, seed) for seed in seeds}
        backwards = {seed: sample(tiny_model, seed) for seed in shuffled}
        assert forwards == backwards

    @SEEDING
    @given(
        seeds=st.lists(valid_seeds, min_size=2, max_size=3, unique=True),
        repeats=st.integers(2, 3),
    )
    def test_one_chain_samples_reproducibly_however_often_it_is_invoked(
        self, tiny_model, seeds, repeats
    ):
        """The run loop builds one chain per (model, seed) and invokes it for every question."""
        chains = {
            seed: SEED_PROMPT | seed_model(tiny_model, seed) | StrOutputParser() for seed in seeds
        }
        first = {seed: chain.invoke({"x": "hello"}) for seed, chain in chains.items()}
        for _ in range(repeats):  # interleave the chains: no call may disturb another
            for seed, chain in chains.items():
                assert chain.invoke({"x": "hello"}) == first[seed]

    @SEEDING
    @given(seed=st.integers(-(2**40), 2**40))
    @example(seed=-1)
    @example(seed=2**32)
    def test_any_integer_is_a_usable_seed(self, tiny_model, seed):
        try:
            ExperimentParameters(seeds=[seed])
        except ValidationError:
            return  # a seed that is rejected up front is not used, which is also fine
        assert sample(tiny_model, seed) == sample(tiny_model, seed)
