# ===========================================================================
#                              Parser Utils
# ===========================================================================
# Utility functions for implementing parsers used for cleaning and
# validating model outputs.


import json
import os
import re
import warnings
from difflib import SequenceMatcher
from typing import Any


def check_span(
    text: str,
    filter_dictionary: dict[str, list[str]],
    span: tuple[int, int] | None = None,
    ratio: float | None = None,
) -> dict[str, Any]:
    """
    Checks the occurrence of specified answers in the text within a defined span or ratio of the text length.

    Args:
        text (str): The input text to search.
        filter_dictionary (dict[str, list[str]]): A dictionary where the keys are categories and the values are lists of answers to check for in the text.
        span (tuple[int, int], optional): A tuple defining the start and end positions within the text to search. Defaults to None.
        ratio (float, optional): A ratio (0.0 to 1.0) of the text length to define the portion of the text to search. Negative ratios start from the end of the text. Defaults to None.

    Returns:
        dict[str, bool]: A dictionary where keys are the categories and values are booleans indicating if any answers were found in the specified span or ratio of the text.
    """
    text = str(text)
    if span:
        start, end = span
        sub_text = text[start:end]
    elif ratio:
        length = int(len(text) * abs(ratio))
        sub_text = text[:length] if ratio > 0 else text[max(len(text) - length, 0) :]
    else:
        sub_text = text

    result = {}
    for category, answers in filter_dictionary.items():
        result[category] = any(answer.lower() in sub_text.lower() for answer in answers)

    return result


def prompt_cleaner(
    prompt,
    completion,
    fast: bool = True,
    similarity_threshold: float = 0.5,
    junk: str | None = None,
) -> dict[str, Any]:
    """Cleans the model's output by trimming repeated sections of the input prompt.

    This function identifies and removes any part of the model's output (`completion`) that closely matches a section of the input `prompt`. The goal is to clean the output by eliminating unnecessary repetitions.

    Args:
        prompt (str): The original input prompt.
        completion (str): The output generated by the model.
        fast (bool): If True, uses a faster but less precise similarity calculation, tends to result with higher scores. Defaults to True.
        similarity_threshold (float): The similarity threshold (between 0 and 1) above which a repeated section is considered for removal. Defaults to 0.5.
        junk (str): A string containing characters to be ignored when considering matches (e.g., whitespace, punctuation). Defaults to " \t\n.,;:!?".

    Returns:
        dict: A dictionary with two keys:
            - 'completion' (str): The cleaned output with any repeated prompt sections removed.
            - 'similarity_score' (float): The similarity score between the prompt and the completion.
            - 'similarity_threshold' (float): The similarity threshold that was set for the processing.
    """

    if similarity_threshold <= 0:
        warnings.warn(
            "similarity_threshold must be greater than 0. Setting it to 0.001.", stacklevel=2
        )
        similarity_threshold = 0.001

    def mini_preprocess(txt):
        return txt.lower().strip()

    prompt, completion = mini_preprocess(prompt), mini_preprocess(completion)

    if junk:

        def isjunk(x):
            return x in junk

        matcher = SequenceMatcher(isjunk=isjunk, a=prompt, b=completion)
    else:
        matcher = SequenceMatcher(a=prompt, b=completion)

    if fast:
        ratio = matcher.real_quick_ratio()
    else:
        ratio = matcher.ratio()

    blocks = [block for block in matcher.get_matching_blocks() if block.size > 0]
    # only strip the prompt if the completion actually starts with (a copy of) it
    if blocks and blocks[0].b == 0 and ratio >= similarity_threshold:
        completion = completion[len(prompt) :].strip()

    return {
        "completion": completion,
        "similarity_score": round(ratio, 3),
        "similarity_threshold": similarity_threshold,
    }


def process_completion(
    text: str,
    pattern_name: str | None = None,
    regex_dict_path: str | None = None,
    user_input_pattern: str | None = None,
) -> list:
    """
    Process the text using a specified regex pattern.

    Args:
        text (str): The input text to be processed.
        pattern_name (str, optional): The name of the pattern to use from the regex dictionary ("numeric_alpha", "alpha_alpha", "numeric_numeric").
        regex_dict_path (str, optional): The path to a JSON file containing regex patterns.
        user_input_pattern (str, optional): A regex pattern provided by the user.

    Returns:
        list: A list of matched groups from the text based on the specified pattern.

    Raises:
        ValueError: If none of pattern_name, regex_dict_path, or user_input_pattern are provided.
        ValueError: If the specified pattern_name does not exist in the default or provided regex dictionary.
    """
    # Default patterns
    default_patterns = {
        "numeric_alpha": r"(\d+)([.,])(.+)",
        "alpha_alpha": r"([A-Za-z]+)([.,])(.+)",
        "numeric_numeric": r"(\d+)([.,])(\s*\d+)",
    }

    if user_input_pattern:
        pattern = user_input_pattern

    elif regex_dict_path:
        with open(regex_dict_path) as file:
            patterns = json.load(file)
            if pattern_name in patterns:
                pattern = patterns[pattern_name]
            else:
                raise ValueError(
                    f"Pattern name '{pattern_name}' not found in the provided regex dictionary."
                )

    elif pattern_name:
        if pattern_name in default_patterns:
            pattern = default_patterns[pattern_name]
        else:
            raise ValueError(
                f"Pattern name '{pattern_name}' not found in the default regex dictionary."
            )

    else:
        raise ValueError(
            "You must provide either pattern_name, regex_dict_path, or user_input_pattern."
        )

    return [
        item.strip()
        for match in re.findall(pattern, text)
        for item in (match if isinstance(match, tuple) else (match,))
    ]


# def check_multiple_choice_answers(text: str, possible_answers: list[str]) -> dict:
#     """
#     Checks for the presence of possible multiple-choice answers in the given text.
#     It counts occurrences of parts of each answer as valid detections.

#     Args:
#         text (str): The input text to search within.
#         possible_answers (list[str]): A list of possible answer strings to check for.

#     Returns:
#         dict: A dictionary where keys are the possible answers and values are the count of detections in the text.
#     """

#     text = text.lower()

#     answer_counts = {answer: 0 for answer in possible_answers}

#     split_pattern = r'(\d+|[a-zA-Z]+|[^a-zA-Z0-9\s])'

#     for answer in possible_answers:
#         normalized_answer = answer.lower()
#         components = [component.strip() for component in re.findall(
#             split_pattern, normalized_answer) if component.strip()]
#         for component in components:
#             match_pattern = fr"\b{re.escape(component)}\b"
#             matches = re.findall(match_pattern, text)
#             answer_counts[answer] += len(matches)
#     return dict(answer_counts)


def check_multiple_choice_answers(
    text: str, possible_answers: list[str], ignore_case: bool = True
) -> dict:
    """
    Checks for the presence of possible multiple-choice answers in the given text.
    Separates the number from the rest of the answer option and removes punctuation.

    Args:
        text (str): The input text to search within.
        possible_answers (list[str]): A list of possible answer strings to check for.

    Returns:
        dict: A dictionary where keys are the possible answers and values are the count of detections in the text.
    """

    text = text.lower() if ignore_case else text
    answer_counts = {answer: 0 for answer in possible_answers}

    # Matches a number or letter at start followed by one of four punctuations or a space <- added more patterns
    enumeration_pattern = r"^(\d+|[a-zA-Z])(?:\.| *= *| *: *| *- *| +)"
    # Matches punctuation at beginning
    punctuation_pattern = r"[^\w\s]"

    def squash(value: str) -> str:
        # Punctuation separates tokens ("answer:3"): replace it by a space and collapse whitespace.
        # Applied to the answer and to the options, so an option still matches itself
        # (e.g. "neutral (neither agree nor disagree)").
        return re.sub(r"\s+", " ", re.sub(punctuation_pattern, " ", value)).strip()

    text = squash(text)
    text_matches = []  # (start, end, option) of every match of an option's text

    for answer in possible_answers:
        normalized_answer = answer.lower() if ignore_case else answer
        enumeration_match = re.match(enumeration_pattern, normalized_answer)

        # If a number is found, split it from the rest of the text and remove punctuation
        enumeration = enumeration_match.group(1) if enumeration_match else None
        answer_text = squash(re.sub(enumeration_pattern, "", normalized_answer))

        # Refine matching logic: only match numbers exactly and ensure full word matching for text
        if enumeration:
            answer_counts[answer] += len(re.findall(rf"\b{re.escape(enumeration)}\b", text))
        if answer_text:
            for match in re.finditer(rf"\b{re.escape(answer_text)}\b", text):
                text_matches.append((match.start(), match.end(), answer))

    # A text match inside the (longer) match of another option counts for that option only:
    # "Strongly agree" must not also be a hit for "Agree".
    for start, end, answer in text_matches:
        covered = any(
            other != answer and o_start <= start and end <= o_end and o_end - o_start > end - start
            for o_start, o_end, other in text_matches
        )
        if not covered:
            answer_counts[answer] += 1

    return answer_counts


def mk_age_keywords(max_age: int = 100) -> list[list]:
    """
    Return a list that contains (in order) for each number in the specified range a list of all
    common expectable representations of that number as stings.

    For expample for the range 0-44:
    [['0', 'nil', 'nought', 'oh', 'zero'] ... ['44', 'forty four', 'forty-four', 'fortyfour']].
    """
    from num2words import num2words

    # generate different written forms of a number
    def generate_written_forms(n):
        forms = set()
        # Basic form
        forms.add(num2words(n))

        # Variations with and without hyphens for compound numbers
        base = num2words(n)
        if "-" in base:
            forms.add(base.replace("-", " "))
            forms.add(base.replace("-", ""))

        # Special case for 0
        if n == 0:
            forms.update(["zero", "nought", "nil", "oh"])

        return sorted(forms)

    # Generate the list of lists
    number_list = []
    for i in range(max_age + 1):
        written_forms = generate_written_forms(i)
        entry = [str(i)] + written_forms
        number_list.append(entry)
    return number_list


def check_gender(text: str, ignore_case: bool = True) -> str:
    """
    Judge what gender a model claims to have in its answer.

    Gender can be either 'male', 'female', or 'other'.
    The decision is made by counting the occurences of related words for each of the
    three options. The option that has the highest score wins.
    """
    male_keywords = [
        "man",
        "male",
        "boy",
        "guy",
        "he",
        "him",
        "his",
        "gentleman",
        "sir",
        "mr",
        "masculine",
        "trans man",
        "transgender man",
        "transmasc",
    ]
    female_keywords = [
        "woman",
        "female",
        "girl",
        "lady",
        "she",
        "her",
        "hers",
        "miss",
        "ms",
        "mrs",
        "feminine",
        "trans woman",
        "transgender woman",
        "transfem",
    ]
    other_keywords = [
        "non-binary",
        "nonbinary",
        "nb",
        "enby",
        "genderqueer",
        "genderfluid",
        "agender",
        "bigender",
        "none",
        "pangender",
        "other",
    ]
    answer_counts = {"female": 0, "male": 0, "other": 0}

    text = text.lower() if ignore_case else text
    # words may contain hyphens and apostrophes; every other symbol separates words ("she/her")
    words = re.findall(r"[\w'-]+", text)

    for keyword in female_keywords:
        answer_counts["female"] += 1 if keyword in words else 0
    for keyword in male_keywords:
        answer_counts["male"] += 1 if keyword in words else 0
    for keyword in other_keywords:
        answer_counts["other"] += 1 if keyword in words else 0

    # pprint(answer_counts)

    max_value = max(answer_counts.values())
    if max_value == 0:
        return "not present"
    else:
        # Find all options with the max_value
        max_keys = [key for key, value in answer_counts.items() if value == max_value]
        if len(max_keys) > 1:
            return "inconclusive"
        else:
            return max_keys[0]


def check_age(text: str, max_age: int, ignore_case: bool = True) -> str:
    """
    Judge what age a model claims to have in its answer.

    Returns:
        str: string of the decided age in numbers (if judging was successful)

    The decision is made based on the first occurence of a number (either written
    or in numbers) in the sentence. All possible subsequent numbers are ignored.
    """
    forms: dict[str, str] = {}
    for keywords in mk_age_keywords(max_age):
        for form in keywords:
            if form != "oh":  # the interjection "Oh" is not the age 0
                forms.setdefault(form, keywords[0])

    text = text.lower() if ignore_case else text
    # hyphens and every other symbol separate words: "twenty-one" -> "twenty one", "18-year-old"
    words = re.findall(r"[A-Za-z0-9]+", text)

    # search first instance of any form of number, longest spelling first ("twenty five" != "twenty")
    for start in range(len(words)):
        for length in (4, 3, 2, 1):
            candidate = " ".join(words[start : start + length])
            if candidate in forms:
                return forms[candidate]
    return "inconclusive"


def split_on_symbols(text: str) -> list[str]:
    """
    Splits the input text based on numbers, special characters, and symbols.

    Args:
        text (str): The input string to split.

    Returns:
        list[str]: A list of non-empty components split by numbers, special characters, and symbols.
    """
    # Regex pattern to split on numbers, special characters, and symbols
    pattern = r"[\W_]+|\d+"

    # Split the text and filter out any empty components
    components = [component for component in re.split(pattern, text) if component]

    return components


def json_saver(data: dict, name: str = "output", path: str = "") -> None:
    """
    Save a dictionary as a JSON file at the specified path and file name.
    If no path is provided, saves to the current directory.
    Prints the full path upon successful save.

    Args:
        data (dict): Dictionary to save as JSON.
        name (str, optional): Name of the file to save. Defaults to 'output'.
        path (str, optional): Directory path where the file will be saved. Defaults to the current directory.

    Returns:
        None
    """
    # Use current directory if no path is provided
    if not path:
        path = os.getcwd()
    if not name.endswith(".json"):
        full_path = os.path.join(path, f"{name}.json")
    else:
        full_path = os.path.join(path, f"{name}")
    payload = json.dumps(data, indent=4)  # serialise first: a failure must not truncate the file
    with open(full_path, "w", encoding="utf-8") as file:
        file.write(payload)
    print(f"File saved successfully at: {full_path}")
